In [1]:
import pandas as pd
df = pd.read_csv('train.csv')
df

               일시  최고기온  최저기온   일교차  강수량  평균습도  평균풍속  일조합    일사합   일조율  평균기온
0      1960-01-01   2.2  -5.2   7.4  NaN  68.3   1.7  6.7    NaN   NaN  -1.6
1      1960-01-02   1.2  -5.6   6.8  0.4  87.7   1.3  0.0    NaN   NaN  -1.9
2      1960-01-03   8.7  -2.1  10.8  0.0  81.3   3.0  0.0    NaN   NaN   4.0
3      1960-01-04  10.8   1.2   9.6  0.0  79.7   4.4  2.6    NaN   NaN   7.5
4      1960-01-05   1.3  -8.2   9.5  NaN  44.0   5.1  8.2    NaN   NaN  -4.6
...           ...   ...   ...   ...  ...   ...   ...  ...    ...   ...   ...
23006  2022-12-27   3.3  -7.3  10.6  NaN  69.8   1.8  8.8  10.25  91.7  -2.6
23007  2022-12-28   0.1  -6.0   6.1  0.1  58.1   2.5  8.7  10.86  90.6  -3.3
23008  2022-12-29   2.1  -7.8   9.9  0.0  56.3   1.7  9.0  10.88  93.8  -2.9
23009  2022-12-30   2.3  -4.4   6.7  0.0  65.6   1.9  7.9  10.84  82.3  -1.8
23010  2022-12-31   2.1  -5.1   7.2  0.0  65.5   1.4  1.1   4.16  11.5  -1.2

[23011 rows x 11 columns]

In [2]:
sub = pd.read_csv('sample_submission.csv')
sub

             일시  평균기온
0    2023-01-01     0
1    2023-01-02     0
2    2023-01-03     0
3    2023-01-04     0
4    2023-01-05     0
..          ...   ...
353  2023-12-20     0
354  2023-12-21     0
355  2023-12-22     0
356  2023-12-23     0
357  2023-12-24     0

[358 rows x 2 columns]

In [3]:
df['강수량'] = df['강수량'].fillna(0)
df

               일시  최고기온  최저기온   일교차  강수량  평균습도  평균풍속  일조합    일사합   일조율  평균기온
0      1960-01-01   2.2  -5.2   7.4  0.0  68.3   1.7  6.7    NaN   NaN  -1.6
1      1960-01-02   1.2  -5.6   6.8  0.4  87.7   1.3  0.0    NaN   NaN  -1.9
2      1960-01-03   8.7  -2.1  10.8  0.0  81.3   3.0  0.0    NaN   NaN   4.0
3      1960-01-04  10.8   1.2   9.6  0.0  79.7   4.4  2.6    NaN   NaN   7.5
4      1960-01-05   1.3  -8.2   9.5  0.0  44.0   5.1  8.2    NaN   NaN  -4.6
...           ...   ...   ...   ...  ...   ...   ...  ...    ...   ...   ...
23006  2022-12-27   3.3  -7.3  10.6  0.0  69.8   1.8  8.8  10.25  91.7  -2.6
23007  2022-12-28   0.1  -6.0   6.1  0.1  58.1   2.5  8.7  10.86  90.6  -3.3
23008  2022-12-29   2.1  -7.8   9.9  0.0  56.3   1.7  9.0  10.88  93.8  -2.9
23009  2022-12-30   2.3  -4.4   6.7  0.0  65.6   1.9  7.9  10.84  82.3  -1.8
23010  2022-12-31   2.1  -5.1   7.2  0.0  65.5   1.4  1.1   4.16  11.5  -1.2

[23011 rows x 11 columns]

In [4]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
print(df)

IndentationError: expected an indented block (3441945574.py, line 2)

In [5]:
df = df.loc[df['일시'] >= '2000-01-01']
df.reset_index(drop=True, inplace=True)
df

              일시  최고기온  최저기온   일교차   강수량  평균습도  평균풍속  일조합    일사합   일조율  평균기온
0     2000-01-01   9.9   1.8   8.1   0.0  63.5   2.3  2.3   4.46  24.0   5.5
1     2000-01-02   6.9  -0.9   7.8   6.0  74.3   3.6  2.2   2.76  22.9   4.2
2     2000-01-03   0.1  -4.6   4.7   0.0  54.1   2.7  5.4   5.11  56.3  -2.2
3     2000-01-04   4.3  -4.3   8.6   0.0  48.6   1.7  1.6   3.59  16.7   0.3
4     2000-01-05   4.6   0.1   4.5  18.4  83.6   3.2  0.0   0.69   0.0   2.8
...          ...   ...   ...   ...   ...   ...   ...  ...    ...   ...   ...
8396  2022-12-27   3.3  -7.3  10.6   0.0  69.8   1.8  8.8  10.25  91.7  -2.6
8397  2022-12-28   0.1  -6.0   6.1   0.1  58.1   2.5  8.7  10.86  90.6  -3.3
8398  2022-12-29   2.1  -7.8   9.9   0.0  56.3   1.7  9.0  10.88  93.8  -2.9
8399  2022-12-30   2.3  -4.4   6.7   0.0  65.6   1.9  7.9  10.84  82.3  -1.8
8400  2022-12-31   2.1  -5.1   7.2   0.0  65.5   1.4  1.1   4.16  11.5  -1.2

[8401 rows x 11 columns]

In [27]:
df.interpolate(method='linear', inplace=True)

/tmp/ipykernel_2132770/2868764835.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.interpolate(method='linear', inplace=True)

In [28]:
df['일시'] = pd.to_datetime(df['일시'])

df['년'] = df['일시'].dt.year
df['월'] = df['일시'].dt.month
df['일'] = df['일시'].dt.day

X = df[['년', '월', '일']]
y = df['평균기온']

/tmp/ipykernel_2132770/1793585903.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['일시'] = pd.to_datetime(df['일시'])
/tmp/ipykernel_2132770/1793585903.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['년'] = df['일시'].dt.year
/tmp/ipykernel_2132770/1793585903.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['월'] = df['일시'].dt.month
/tmp/ipykernel_2132770/1793585903.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['일'] = df['일시'].dt.day

In [61]:
X.iloc[7900]

년    2021
월       8
일      18
Name: 7900, dtype: int32

선형회귀는 심각하게 별로인거같다(시계열에서는?)

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

X_train, X_test = X[:7670], X[7670:]
y_train, y_test = y[:7670], y[7670:]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train_scaled, y_train)

y_pred_lr = model.predict(X_test_scaled)

mae = mean_absolute_error(y_test, y_pred_lr)
print(f'Mean Absolute Error (MAE): {mae}')

Mean Absolute Error (MAE): 8.856779234983508

model.fit(X_train_reshaped, y_train, epochs=50, batch_size=32, verbose=2)

In [59]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = Sequential()
model.add(LSTM(50, return_sequences=True, input_shape=(X_train_scaled.shape[1], 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error')
        
X_train_reshaped = X_train_scaled.reshape((X_train_scaled.shape[0], X_train_scaled.shape[1], 1))
X_test_reshaped = X_test_scaled.reshape((X_test_scaled.shape[0], X_test_scaled.shape[1], 1))

model.fit(X_train_reshaped, y_train, epochs=50, batch_size=32, verbose=2)
y_pred = model.predict(X_test_reshaped)
y_pred = y_pred.flatten()

# 평가 (예: MAE)
mae = mean_absolute_error(y_test, y_pred)
print(f'Mean Absolute Error (MAE): {mae}')

Epoch 1/50
240/240 - 2s - loss: 212.4899 - 2s/epoch - 7ms/step
Epoch 2/50
240/240 - 1s - loss: 153.9066 - 634ms/epoch - 3ms/step
Epoch 3/50
240/240 - 1s - loss: 141.1182 - 637ms/epoch - 3ms/step
Epoch 4/50
240/240 - 1s - loss: 132.0173 - 658ms/epoch - 3ms/step
Epoch 5/50
240/240 - 1s - loss: 120.9052 - 665ms/epoch - 3ms/step
Epoch 6/50
240/240 - 1s - loss: 104.2641 - 655ms/epoch - 3ms/step
Epoch 7/50
240/240 - 1s - loss: 87.6240 - 632ms/epoch - 3ms/step
Epoch 8/50
240/240 - 1s - loss: 78.1511 - 628ms/epoch - 3ms/step
Epoch 9/50
240/240 - 1s - loss: 72.6832 - 632ms/epoch - 3ms/step
Epoch 10/50
240/240 - 1s - loss: 68.7517 - 640ms/epoch - 3ms/step
Epoch 11/50
240/240 - 1s - loss: 65.6705 - 642ms/epoch - 3ms/step
Epoch 12/50
240/240 - 1s - loss: 63.2203 - 633ms/epoch - 3ms/step
Epoch 13/50
240/240 - 1s - loss: 61.1126 - 658ms/epoch - 3ms/step
Epoch 14/50
240/240 - 1s - loss: 59.1669 - 650ms/epoch - 3ms/step
Epoch 15/50
240/240 - 1s - loss: 57.1880 - 654ms/epoch - 3ms/step
Epoch 16/50
240/240 - 1s - loss: 55.3929 - 620ms/epoch - 3ms/step
Epoch 17/50
240/240 - 1s - loss: 53.8233 - 658ms/epoch - 3ms/step
Epoch 18/50
240/240 - 1s - loss: 52.3619 - 663ms/epoch - 3ms/step
Epoch 19/50
240/240 - 1s - loss: 51.0640 - 659ms/epoch - 3ms/step
Epoch 20/50
240/240 - 1s - loss: 49.9659 - 665ms/epoch - 3ms/step
Epoch 21/50
240/240 - 1s - loss: 48.9741 - 651ms/epoch - 3ms/step
Epoch 22/50
240/240 - 1s - loss: 47.9585 - 642ms/epoch - 3ms/step
Epoch 23/50
240/240 - 1s - loss: 47.0965 - 661ms/epoch - 3ms/step
Epoch 24/50
240/240 - 1s - loss: 46.4378 - 647ms/epoch - 3ms/step
Epoch 25/50
240/240 - 1s - loss: 45.9287 - 648ms/epoch - 3ms/step
Epoch 26/50
240/240 - 1s - loss: 45.5415 - 639ms/epoch - 3ms/step
Epoch 27/50
240/240 - 1s - loss: 45.2275 - 657ms/epoch - 3ms/step
Epoch 28/50
240/240 - 1s - loss: 45.0228 - 655ms/epoch - 3ms/step
Epoch 29/50
240/240 - 1s - loss: 44.7934 - 658ms/epoch - 3ms/step
Epoch 30/50
240/240 - 1s - loss: 44.6568 - 678ms/epoch - 3ms/step
Epoch 31/50
240/240 - 1s - loss: 44.5416 - 641ms/epoch - 3ms/step
Epoch 32/50
240/240 - 1s - loss: 44.4287 - 647ms/epoch - 3ms/step
Epoch 33/50
240/240 - 1s - loss: 44.3760 - 641ms/epoch - 3ms/step
Epoch 34/50
240/240 - 1s - loss: 44.3034 - 648ms/epoch - 3ms/step
Epoch 35/50
240/240 - 1s - loss: 44.2641 - 656ms/epoch - 3ms/step
Epoch 36/50
240/240 - 1s - loss: 44.2115 - 659ms/epoch - 3ms/step
Epoch 37/50
240/240 - 1s - loss: 44.1797 - 652ms/epoch - 3ms/step
Epoch 38/50
240/240 - 1s - loss: 44.1580 - 645ms/epoch - 3ms/step
Epoch 39/50
240/240 - 1s - loss: 44.1178 - 639ms/epoch - 3ms/step
Epoch 40/50
240/240 - 1s - loss: 44.1123 - 636ms/epoch - 3ms/step
Epoch 41/50
240/240 - 1s - loss: 44.0989 - 649ms/epoch - 3ms/step
Epoch 42/50
240/240 - 1s - loss: 44.0415 - 650ms/epoch - 3ms/step
Epoch 43/50
240/240 - 1s - loss: 44.0405 - 642ms/epoch - 3ms/step
Epoch 44/50
240/240 - 1s - loss: 44.0034 - 638ms/epoch - 3ms/step
Epoch 45/50
240/240 - 1s - loss: 43.9932 - 651ms/epoch - 3ms/step
Epoch 46/50
240/240 - 1s - loss: 43.9714 - 655ms/epoch - 3ms/step
Epoch 47/50
240/240 - 1s - loss: 43.9619 - 662ms/epoch - 3ms/step
Epoch 48/50
240/240 - 1s - loss: 43.9845 - 668ms/epoch - 3ms/step
Epoch 49/50
240/240 - 1s - loss: 43.9481 - 661ms/epoch - 3ms/step
Epoch 50/50
240/240 - 1s - loss: 43.9470 - 649ms/epoch - 3ms/step
23/23 [==============================] - 0s 2ms/step

ValueError: Found input variables with inconsistent numbers of samples: [731, 2193]

In [55]:
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svr_model = SVR(kernel='rbf', C=180, gamma='scale')
svr_model.fit(X_train_scaled, y_train)

y_pred_svr = svr_model.predict(X_test_scaled)
mae_svr = mean_absolute_error(y_test, y_pred_svr)
print(f'Mean Absolute Error (MAE): {mae_svr}')

Mean Absolute Error (MAE): 3.311535896492727

In [51]:
y_pred_svr

array([-1.49279741e+00, -3.31886173e+00, -3.33579512e+00, -3.29963918e+00,
       -3.21197047e+00, -3.07440577e+00, -2.88849897e+00, -2.65572432e+00,
       -2.37755108e+00, -2.05560224e+00, -1.69187913e+00, -1.28902357e+00,
       -8.50582357e-01, -3.81236262e-01,  1.13043194e-01,  6.24939741e-01,
        1.14586212e+00,  1.66614605e+00,  2.17538293e+00,  2.66285615e+00,
        3.11805380e+00,  3.53121785e+00,  3.89388485e+00,  4.19937320e+00,
        4.44317596e+00,  4.62322672e+00,  4.74001699e+00,  4.79655666e+00,
        4.79818212e+00,  4.75222926e+00,  4.66759821e+00,  4.55424430e+00,
       -3.23853822e-01, -2.70090218e-01, -1.67104254e-01, -1.74371835e-02,
        1.75849592e-01,  4.09347352e-01,  6.79441515e-01,  9.82409796e-01,
        1.31447153e+00,  1.67178967e+00,  2.05043367e+00,  2.44631731e+00,
        2.85512893e+00,  3.27227319e+00,  3.69284188e+00,  4.11162769e+00,
        4.52318924e+00,  4.92196851e+00,  5.30245498e+00,  5.65938425e+00,
        5.98795373e+00,  6.28403574e+00,  6.54436737e+00,  6.76669927e+00,
        6.94988906e+00,  7.09393119e+00,  7.19992140e+00,  7.26995989e+00,
        4.19601571e+00,  4.33252003e+00,  4.50956532e+00,  4.72421709e+00,
        4.97247359e+00,  5.24946874e+00,  5.54971230e+00,  5.86735070e+00,
        6.19643126e+00,  6.53115361e+00,  6.86609414e+00,  7.19639260e+00,
        7.51789327e+00,  7.82723668e+00,  8.12190130e+00,  8.40019718e+00,
        8.66121564e+00,  8.90474085e+00,  9.13112978e+00,  9.34116809e+00,
        9.53590993e+00,  9.71651028e+00,  9.88405883e+00,  1.00394250e+01,
        1.01831239e+01,  1.03152124e+01,  1.04352238e+01,  1.05421478e+01,
        1.06344590e+01,  1.07101950e+01,  1.07670799e+01,  9.66209825e+00,
        9.88357933e+00,  1.01342791e+01,  1.04117147e+01,  1.07117980e+01,
        1.10290175e+01,  1.13567301e+01,  1.16875428e+01,  1.20137591e+01,
        1.23278580e+01,  1.26229705e+01,  1.28933170e+01,  1.31345738e+01,
        1.33441397e+01,  1.35212806e+01,  1.36671421e+01,  1.37846251e+01,
        1.38781331e+01,  1.39532070e+01,  1.40160728e+01,  1.40731339e+01,
        1.41304427e+01,  1.41931915e+01,  1.42652582e+01,  1.43488420e+01,
        1.44442162e+01,  1.45496192e+01,  1.46612921e+01,  1.47736643e+01,
        1.48796729e+01,  1.53018603e+01,  1.55994122e+01,  1.59135628e+01,
        1.62430316e+01,  1.65845186e+01,  1.69328250e+01,  1.72811435e+01,
        1.76215017e+01,  1.79453266e+01,  1.82440867e+01,  1.85099608e+01,
        1.87364765e+01,  1.89190654e+01,  1.90554841e+01,  1.91460638e+01,
        1.91937615e+01,  1.92040034e+01,  1.91843276e+01,  1.91438489e+01,
        1.90925831e+01,  1.90406812e+01,  1.89976308e+01,  1.89714841e+01,
        1.89681751e+01,  1.89909766e+01,  1.90401421e+01,  1.91127624e+01,
        1.92028491e+01,  1.93016420e+01,  1.93981190e+01,  1.94796720e+01,
        2.02468666e+01,  2.05975764e+01,  2.09511638e+01,  2.13078414e+01,
        2.16656358e+01,  2.20204342e+01,  2.23662368e+01,  2.26956026e+01,
        2.30002532e+01,  2.32717861e+01,  2.35024360e+01,  2.36858179e+01,
        2.38175838e+01,  2.38959312e+01,  2.39219147e+01,  2.38995263e+01,
        2.38355292e+01,  2.37390526e+01,  2.36209723e+01,  2.34931229e+01,
        2.33674010e+01,  2.32548277e+01,  2.31646450e+01,  2.31035170e+01,
        2.30749018e+01,  2.30786438e+01,  2.31108227e+01,  2.31638747e+01,
        2.32269773e+01,  2.32866753e+01,  2.36256928e+01,  2.39906739e+01,
        2.43437613e+01,  2.46863118e+01,  2.50176537e+01,  2.53350831e+01,
        2.56340716e+01,  2.59086724e+01,  2.61520915e+01,  2.63573731e+01,
        2.65181388e+01,  2.66293116e+01,  2.66877555e+01,  2.66927696e+01,
        2.66463859e+01,  2.65534365e+01,  2.64213767e+01,  2.62598702e+01,
        2.60801637e+01,  2.58942971e+01,  2.57142076e+01,  2.55507984e+01,
        2.54130452e+01,  2.53072119e+01,  2.52362394e+01,  2.51993585e+01,
        2.51919610e+01,  2.52057437e+01,  2.52291193e+01,  2.52478656e+01,
        2.52459713e+01,  2.46868492e+01,  2.50147269e+01,  2.53164458e+01,
        2.55936177e+01,  2.58462813e+01,  2.60729039e+01,  2.62705668e+01,
        2.64353184e+01,  2.65626629e+01,  2.66481392e+01,  2.66879335e+01,
        2.66794681e+01,  2.66219065e+01,  2.65165258e+01,  2.63669145e+01,
        2.61789736e+01,  2.59607112e+01,  2.57218405e+01,  2.54732088e+01,
        2.52260956e+01,  2.49914338e+01,  2.47790103e+01,  2.45967074e+01,
        2.44498443e+01,  2.43406699e+01,  2.42680491e+01,  2.42273701e+01,
        2.42106851e+01,  2.42070804e+01,  2.42032529e+01,  2.41842576e+01,
        2.29708684e+01,  2.32093169e+01,  2.34118695e+01,  2.35792965e+01,
        2.37114019e+01,  2.38070985e+01,  2.38646110e+01,  2.38817900e+01,
        2.38565024e+01,  2.37870596e+01,  2.36726408e+01,  2.35136682e+01,
        2.33120969e+01,  2.30715882e+01,  2.27975484e+01,  2.24970235e+01,
        2.21784542e+01,  2.18513048e+01,  2.15255912e+01,  2.12113367e+01,
        2.09179933e+01,  2.06538646e+01,  2.04255697e+01,  2.02375825e+01,
        2.00918792e+01,  1.99877189e+01,  1.99215754e+01,  1.98872308e+01,
        1.98760288e+01,  1.98772795e+01,  1.84916224e+01,  1.86041290e+01,
        1.86812173e+01,  1.87219260e+01,  1.87248571e+01,  1.86883766e+01,
        1.86108797e+01,  1.84910939e+01,  1.83283862e+01,  1.81230425e+01,
        1.78764911e+01,  1.75914477e+01,  1.72719695e+01,  1.69234135e+01,
        1.65523055e+01,  1.61661300e+01,  1.57730601e+01,  1.53816456e+01,
        1.50004797e+01,  1.46378612e+01,  1.43014685e+01,  1.39980550e+01,
        1.37331765e+01,  1.35109566e+01,  1.33338975e+01,  1.32027416e+01,
        1.31163925e+01,  1.30719029e+01,  1.30645362e+01,  1.30879086e+01,
        1.31342141e+01,  1.18350845e+01,  1.18152004e+01,  1.17754435e+01,
        1.17127512e+01,  1.16238509e+01,  1.15056058e+01,  1.13553684e+01,
        1.11713035e+01,  1.09526478e+01,  1.06998796e+01,  1.04147840e+01,
        1.01004128e+01,  9.76094920e+00,  9.40149962e+00,  9.02784172e+00,
        8.64615945e+00,  8.26279512e+00,  7.88404126e+00,  7.51598612e+00,
        7.16441529e+00,  6.83476162e+00,  6.53208700e+00,  6.26107444e+00,
        6.02600812e+00,  5.83072253e+00,  5.67850906e+00,  5.57197784e+00,
        5.51288342e+00,  5.50193209e+00,  5.53859593e+00,  4.09014523e+00,
        3.96522786e+00,  3.85216273e+00,  3.74603523e+00,  3.64151685e+00,
        3.53333619e+00,  3.41671890e+00,  3.28775118e+00,  3.14363134e+00,
        2.98278862e+00,  2.80486594e+00,  2.61058137e+00,  2.40149863e+00,
        2.17974852e+00,  1.94774853e+00,  1.70796615e+00,  1.46276336e+00,
        1.21434554e+00,  9.64820655e-01,  7.16356033e-01,  4.71403179e-01,
        2.32948337e-01,  4.74016953e-03, -2.08553533e-01, -4.01300400e-01,
       -5.66995767e-01, -6.98501191e-01, -7.88418109e-01, -8.29566968e-01,
       -8.15527139e-01, -7.41183464e-01])

In [56]:
sub['평균기온'] = y_pred_svr[-358:]
sub

             일시      평균기온
0    2023-01-01  0.575970
1    2023-01-02  0.611613
2    2023-01-03  0.700923
3    2023-01-04  0.865998
4    2023-01-05  1.124109
..          ...       ...
353  2023-12-20  0.285587
354  2023-12-21  0.354353
355  2023-12-22  0.426477
356  2023-12-23  0.525233
357  2023-12-24  0.675046

[358 rows x 2 columns]

In [57]:
sub.to_csv("svr2_submission.csv", index=False)